#ifndef _ADVECTION_METHOD_H_
#define _ADVECTION_METHOD_H_

enum AdvectionMethod
{
    SEMI_LAGRANGIAN,
    MACCORMACK_SEMI_LAGRANGIAN,
    BFECC_SEMI_LAGRANGIAN,

    INVALID_ADVECTION_METHOD
};

#endif // _ADVECTION_METHOD_H_